/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}/components` | `/tabs/components`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}/details` | `/tabs/details`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}/edit` | `/tabs/edit`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}/settings` | `/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}/account` | `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}/privacy` | `/tabs/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(home)'}/components` | `/tabs/components`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(home)'}/details` | `/tabs/details`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(home)'}` | `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(profile)'}/edit` | `/tabs/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(profile)'}` | `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(profile)'}/settings` | `/tabs/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(settings)'}/account` | `/tabs/account`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(settings)'}` | `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs${'/(settings)'}/privacy` | `/tabs/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/tabs${'/(home)'}/components${`?${string}` | `#${string}` | ''}` | `/tabs/components${`?${string}` | `#${string}` | ''}` | `/tabs${'/(home)'}/details${`?${string}` | `#${string}` | ''}` | `/tabs/details${`?${string}` | `#${string}` | ''}` | `/tabs${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs${'/(profile)'}/edit${`?${string}` | `#${string}` | ''}` | `/tabs/edit${`?${string}` | `#${string}` | ''}` | `/tabs${'/(profile)'}${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs${'/(profile)'}/settings${`?${string}` | `#${string}` | ''}` | `/tabs/settings${`?${string}` | `#${string}` | ''}` | `/tabs${'/(settings)'}/account${`?${string}` | `#${string}` | ''}` | `/tabs/account${`?${string}` | `#${string}` | ''}` | `/tabs${'/(settings)'}${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs${'/(settings)'}/privacy${`?${string}` | `#${string}` | ''}` | `/tabs/privacy${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}/components` | `/tabs/components`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}/details` | `/tabs/details`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(home)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}/edit` | `/tabs/edit`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(profile)'}/settings` | `/tabs/settings`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}/account` | `/tabs/account`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}` | `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs${'/(settings)'}/privacy` | `/tabs/privacy`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
